repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: \.py$
        args: ["--profile", "black"]

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        files: \.py$
        exclude: __init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|h|hpp|cu|cuh|xpu)$
        args:
          - --style=file

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: \.py$
        args: ["--line-length=120"]
